### ISSUE TITLE
Update docs to run Rococo relay chain 

### ISSUE THREAD

**Issue by nakul1010** [interlay/interbtc#1241]
## Problem

The current documentation for running the Rococo locally can be found [here](https://github.com/interlay/interbtc/blob/master/docs/rococo.md).

The testnet is down because the relay chain is still using a very old local commit and not the newer Polkadot version. Therefore, we need to use a new relay chain version.

- [Polkadot launch](https://github.com/paritytech/polkadot-launch): We used thisin doc, but the CLI tool is now deprecated.

## Solution

To launch using Zombienet, follow these necessary steps:

### Step 1: Download and Build Polkadot-SDK

```shell
git clone https://github.com/paritytech/polkadot-sdk.git
cd polkadot-sdk

git fetch --all --tags
git checkout tags/polkadot-v1.13.0

cargo build --release

cd ..
```

### Step 2: Download and Build InterBTC

```shell
git clone https://github.com/interlay/interbtc.git
cd interbtc

git fetch --all --tags
git checkout tags/1.25.4

cargo build --release

cd ..
```

### Step 3: Download Zombienet

Download [Zombienet](https://github.com/paritytech/zombienet/releases/tag/v1.3.105) for the Linux version.

- Steps to setup Zombienet can be found in this [article](https://hackmd.io/@brunopgalvao/S1Ilj5zA5#Setting-up-Zombienet).

```shell
mkdir deployment_config
cd deployment_config

touch config.toml
```

### Step 4: Configure Zombienet

Copy the following into the `config.toml` file:

```toml
[relaychain]  
default_command =  "../polkadot-sdk/target/release/polkadot"  
default_args = [ "-lparachain=debug" ]  
  
chain = "rococo-local"  
  
[[relaychain.nodes]]  
name = "alice"  
validator = true  
  
[[relaychain.nodes]]  
name = "bob"  
validator = true  
rpc_port = 30334
  
[[parachains]]  
id = 2032  
cumulus_based = true  
  
[parachains.collator]  
name = "alice"  
command = "../interbtc/target/release/interbtc-parachain"  
validator = true  
ws_port = 9946
```

### Step 5: Run Zombienet

To run Zombienet, use:

```bash
./zombienet-macos -p native spawn config.toml
```

- Zombienet [configs](https://paritytech.github.io/zombienet/network-definition-spec.html) to hardcode ports, etc.

### Hardcode Default Chain

- Currently, it will start the Kintsugi parachain. To start the Interlay testnet chain, update the spec [here](https://github.com/interlay/interbtc/blob/9ae20ea66174556c4d31187765f1abb9f6c42fad/parachain/src/command.rs#L71) to `chain_spec::testnet_interlay::staging_mainnet_config(false)`.
- Need to find a way to specify the chain in the config file. Zombienet itself creates a `chainspec.json` based on `chain = "rococo-local"`. Adding `chain` as arguments creates a wrong command.

### Docker Images for SDK 

- Instead of compiling the repos, use Docker images instead. Didn't find any other projects using it. 

---
